### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character

### ISSUE THREAD

**Issue by mauroturner** [N0rz3/Eyes#3]
This error is caused by special characters such as: ├──, └── and emojis.

**Comment by N0rz3** [comment]
sorry but I can't solve the error, this may be caused by your terminal may be too old if windows 10 or less otherwise I can't do anything about it

**Comment by N0rz3** [comment]
therwise try to remove emojis and characters (├──, └──) from the code

**Comment by mauroturner** [comment]
Yes, that's what I did, and it worked. I started this thread in case someone else had the same issue. Thanks
